### ISSUE TITLE
API features

### ISSUE THREAD

**Issue by cybershambles** [donorbox/donorbox-api#1]
Please support the following in order of importance:

1) I need the donations API to be sorted newest to oldest with pagination
eg: `https://donorbox.org/api/v1/donations?order=newest`

2) I need to be able to pull donations from X campaign instead of a stream of all campaigns
eg: `https://donorbox.org/api/v1/donations?campaignid=33484`

3) I need the pagination size to be changed from the default 50 to 1-100?
eg: `https://donorbox.org/api/v1/donations?per_page=100`

I also need to be able to use these combined
eg: `https://donorbox.org/api/v1/donations?order=newest;campaignid=33484;per_page=100`

Thanks.

**Comment by cybershambles** [comment]
Slightly updated

**Comment by henry2992** [comment]
@cybershambles please refer to the new documentation.

**Comment by cybershambles** [comment]
Thank you very much.
