### ISSUE TITLE
403 Forbidden (error code: 1005)

### ISSUE THREAD

**Issue by lukecyca** [donorbox/donorbox-api#23]
When I access the API from my VPS, I get a 403 Forbidden response with the body:
```
error code: 1005
```

In this case I am accessing `/api/v1/donors`. The same code works fine when run locally on a computer on a residential Internet connection.

I know from testing that the error for invalid authentication is different.

What is "error code: 1005"? Some sort of rate limiting error? IP blacklist?

**Comment by adrianbj** [comment]
I am seeing the exact same issue. Works fine if I make a CURL request from my local dev machine or via a browser direct call, but via Digital Ocean server I get the 1005 error.

@lukecyca - did you ever solve this?

@hussainakram - any chance you could chime in please? Is there a list of error codes and what they mean?

**Comment by adrianbj** [comment]
I little more digging shows that it's a 403 forbidden. How do we deal with that please? Do you maintain a blocklist that my VPS might be on?

**Comment by lukecyca** [comment]
If I recall correctly, I was also using DigitalOcean when I got this issue. Perhaps they are blocking DigitalOcean's IP space.

I "resolved" it by consuming their API from elsewhere.

**Comment by adrianbj** [comment]
Thanks @lukecyca - it's a real shame we can't get any action on this matter more than a year on.

**Comment by adrianbj** [comment]
@hussainakram - can we possibly get some official input about this issue please?

**Comment by HugoGresse** [comment]
I've contacted the Donorbox team through their website. 
On top of not allowing all origins (CORS) which even paypal allow, asking for 17$/month on top of the cut they already take from each donation, this is incredible.

**Comment by HugoGresse** [comment]
so, it seems server IPs can be authorized when asking to donorbox team directly.

**Comment by hussainakram** [comment]
I apologize for the delay in our response! Occasionally, IP addresses may be temporarily blocked for security purposes. However, if you have a registered account with us, please don't hesitate to reach out by opening a support ticket. We'll be more than happy to assist you and ensure that your IP addresses are added to our whitelist.
