### ISSUE TITLE
donations api missing designations

### ISSUE THREAD

**Issue by cybershambles** [donorbox/donorbox-api#4]
The designations are missing from the donations.

**Comment by cybershambles** [comment]
@henry2992 @rebelvc 
this seems to be an oversight... I swear the designations were shown previously

**Comment by cybershambles** [comment]
This wasn't resolved? designation is still missing?

**Comment by henry2992** [comment]
@cybershambles designation is shown on the response

**Comment by cybershambles** [comment]
It's always null. bug?

**Comment by henry2992** [comment]
@cybershambles 

`"designation": "Area of greatest need",`

Maybe the donations were done before adding a designation? I get designation correctly in my requests .

**Comment by cybershambles** [comment]
I can confirm this is working. false alarm
