### ISSUE TITLE
Feature request: is_current_sustainer field on donor objects

### ISSUE THREAD

**Issue by timstallmann** [donorbox/donorbox-api#9]
Would it be possible to add a flag to the donor records indicating whether the donor is currently a sustainer?

**Comment by henry2992** [comment]
@timstallmann do you mean, if it is a recurrent donor?

**Comment by timstallmann** [comment]
Yes, exactly! Would be helpful to have this info on new donors (via Zapier actually, but I'm assuming that would have to be in the API first)

**Comment by henry2992** [comment]
@timstallmann you can get this information in the donation itself. Since a donor might donate to different organizations and campaigns the information will on on the donation.
